force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <label>Weather Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather__c/fields/distance__c.field-meta.xml
<CustomField>
    <fullName>distance__c</fullName>
    <label>distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/latt_long__c.field-meta.xml
<CustomField>
    <fullName>latt_long__c</fullName>
    <label>latt_long</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/location_type__c.field-meta.xml
<CustomField>
    <fullName>location_type__c</fullName>
    <label>location type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Weather__c/fields/woeid__c.field-meta.xml
<CustomField>
    <fullName>woeid__c</fullName>
    <label>woeid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeatherData.cls
public class WeatherData 
{
    public class wrap
    {
        public string title;
        public string location_type;
        public integer woeid;
        public integer distance;
        public string latt_long;
    }
    @Auraenabled
    public static List<Weather__c> call(String picval)
    {
        List<WeatherData.wrap> weatherdetails=new List<WeatherData.wrap>();
        Weather__c weatherobj=new Weather__c();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://www.metaweather.com/api/location/search/?query='+picval);
        request.setHeader('Content-type','accept/json');
        request.setMethod('GET');
        Http http = new Http();
        HttpResponse response = http.send(request);
        String responseBody = response.getBody();
        System.debug('Response:' + responseBody);
        List<WeatherData.wrap> WeatherDatalist=(List<WeatherData.wrap>)JSON.deserialize(responseBody, List<WeatherData.wrap>.class);
        for(WeatherData.wrap wp:WeatherDatalist)
        {
            weatherdetails.add(wp);
            weatherobj.distance__c=wp.distance;
            weatherobj.latt_long__c=wp.latt_long;
            weatherobj.title__c=wp.title;
            weatherobj.woeid__c=wp.woeid;
            weatherobj.location_type__c=wp.location_type;
            insert weatherobj;
        }
        List<Weather__c> weadetail=[SELECT distance__c,woeid__c,location_type__c,latt_long__c,title__c FROM Weather__c WHERE title__c=:picval];
        return weadetail;
    }
    
}